apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: prod/microservices/postgres
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: prod/microservices/postgres
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: prod/microservices/postgres
        property: database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-external-secrets
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: prod/microservices/app
        property: database_url
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: prod/microservices/grafana
        property: admin_user
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: prod/microservices/grafana
        property: admin_password
