apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 2
