apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets/app-secret.yaml
  - postgres/configmap.yaml
  - postgres/secret.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - services/service-c.yaml
  - services/service-c-hpa.yaml
  - services/service-b.yaml
  - services/service-a.yaml
  - services/anomaly-detector.yaml
  - kafka/kafka.yaml
  - logging/loki.yaml
  - logging/fluent-bit-shipper.yaml
  - logging/fluent-bit-consumer.yaml
  - logging/grafana.yaml
  - tracing/jaeger.yaml
  - monitoring/alert-rules.yaml
  - monitoring/prometheus.yaml
  - monitoring/alertmanager.yaml
  - monitoring/kafka-exporter.yaml
